#ifndef __SHELL_CONF_H__
#define __SHELL_CONF_H__

#define CONFIG_SHELL_HISTROY_MAX_COUNT   4
#define CONFIG_SHELL_PARAMETER_MAX_COUNT 12
#define CONFIG_SHELL_PRINTF_BUFSIZE      128
#define CONFIG_SHELL_CMD_HASH_SEED       0xB433E5C6

#endif
